global:
  scrape_interval:     15s

  external_labels:
    monitor: 'blog-monitor'

scrape_configs:
  - job_name: 'blog-exporter'
    scrape_interval: 5s
    metrics_path: '/firehose/resources/metrics'
    static_configs:
      - targets: ['yeti.local:8080']